// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMwO29Cc2x3-unEmMynTU3b8mm_Ov-Ydg',
    appId: '1:326548561404:web:929ad8917e5a5a80a86679',
    messagingSenderId: '326548561404',
    projectId: 'smart-house-ac3b4',
    authDomain: 'smart-house-ac3b4.firebaseapp.com',
    storageBucket: 'smart-house-ac3b4.firebasestorage.app',
    measurementId: 'G-X13ZJQK5YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7AJ3ZOENQ8nbKyuzklXGnS1-0UwnuJM0',
    appId: '1:326548561404:android:84e717d4a9521ef9a86679',
    messagingSenderId: '326548561404',
    projectId: 'smart-house-ac3b4',
    storageBucket: 'smart-house-ac3b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByAmXbvxzZHyJA6hUs0tXJb5C8ze56Hnw',
    appId: '1:326548561404:ios:dbf8381ca9298f0ba86679',
    messagingSenderId: '326548561404',
    projectId: 'smart-house-ac3b4',
    storageBucket: 'smart-house-ac3b4.firebasestorage.app',
    iosBundleId: 'com.example.bothouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByAmXbvxzZHyJA6hUs0tXJb5C8ze56Hnw',
    appId: '1:326548561404:ios:dbf8381ca9298f0ba86679',
    messagingSenderId: '326548561404',
    projectId: 'smart-house-ac3b4',
    storageBucket: 'smart-house-ac3b4.firebasestorage.app',
    iosBundleId: 'com.example.bothouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMwO29Cc2x3-unEmMynTU3b8mm_Ov-Ydg',
    appId: '1:326548561404:web:5b5adc94f4e52e5ea86679',
    messagingSenderId: '326548561404',
    projectId: 'smart-house-ac3b4',
    authDomain: 'smart-house-ac3b4.firebaseapp.com',
    storageBucket: 'smart-house-ac3b4.firebasestorage.app',
    measurementId: 'G-G321WPSKSG',
  );
}
